### ISSUE TITLE
Error on run time after attaching paytm-checksum_2.0.jar in Android Studio 3.0.1

### ISSUE THREAD

**Issue by jenish-jadav** [Paytm-Payments/Paytm_App_Checksum_Kit_JAVA#1]
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /var/www/html/jenish/AndroidStudioProjects/Demo-Apps/PaytmPaymentGateway/app/libs/paytm-checksum_2.0.jar

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing target/test-classes/com/paytm/pg/AppTest.class

Error:com.android.dx.cf.iface.ParseException: class name (com/paytm/pg/AppTest) does not match path (target/test-classes/com/paytm/pg/AppTest.class)

Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /var/www/html/jenish/AndroidStudioProjects/Demo-Apps/PaytmPaymentGateway/app/libs/paytm-checksum_2.0.jar

**Comment by gauravmehta19** [comment]
Better to keep the checksum generation on server not on client.

**Comment by induction2020** [comment]
Hello Paytm Team,
This check generation hash is working fine in java main method,
but in android device it is showing the below exception.

java.lang.NoClassDefFoundError: Failed resolution of: Lsun/misc/BASE64Encode

Please tell me, how to resolve it.
