### ISSUE TITLE
imports can not be resolved

### ISSUE THREAD

**Issue by snehachandiyekar** [Paytm-Payments/Paytm_App_Checksum_Kit_JAVA#2]
Hi, I've downloaded this kit and trying to build it. Getting error as 'import com.paytm.pg.merchant' and 'CheckSumServiceHelper' can not be resolved. Please let me know if any other jar or dependency is to be added.

**Comment by Avinashannand** [comment]
Commit

**Comment by Avinashannand** [comment]
[Paytm_App_Checksum_Kit_JAVA-master.zip](https://github.com/Paytm-Payments/Paytm_App_Checksum_Kit_JAVA/files/2753459/Paytm_App_Checksum_Kit_JAVA-master.zip).

or use this link to https://github.com/Paytm-Payments/Paytm_App_Checksum_Kit_JAVA.

**Comment by naseemali925** [comment]
@Avinashannand I Already Tried Downloading And Using The Files. Maybe You Should Give It A Try Too And Let Us Know If Those Imports Can B Resolved. CheckSumService Isn't There To Be Used.

**Comment by snehachandiyekar** [comment]
> Same Issue @snehachandiyekar Let Me Know If You Have Found A Solution Already.

Yes, using "pg-checksum-1.0-jar-with-dependencies.jar" solved the issue. 
Refer this link: https://github.com/Paytm-Payments/Paytm_Google_App_Engine_Kit

**Comment by Anujkumar12** [comment]
@snehachandiyekar I tried adding "pg-checksum-1.0-jar-with-dependencies.jar" file but I am getting the following error. 
java.lang.NoClassDefFoundError: Failed resolution of: Lsun/misc/BASE64Encoder;
You got any similar error when adding CheckSumServiceHelper class?

Also tried adding "checksum_2.0.0.jar" file & ended up getting this error 
Error: Program type already present: com.paytm.pg.AppTest

**Comment by PrashantM89** [comment]
Your jar is available at compile time, hence no error but at run time your jar file is missing.
Just make sure the jar file is in **/WEB-INF/lib** folder.

Quick dirty way is to copy paste your jar in **/WEB-INF/lib** folder and redeploy your app on server.

**Comment by abhipranayak1998** [comment]
Error: Program type already present: com.paytm.pg.AppTest
This kind of error is showing while giving the output.

**Comment by hrushi8888** [comment]
> [Paytm_App_Checksum_Kit_JAVA-master.zip](https://github.com/Paytm-Payments/Paytm_App_Checksum_Kit_JAVA/files/2753459/Paytm_App_Checksum_Kit_JAVA-master.zip).
> 
> or use this link to https://github.com/Paytm-Payments/Paytm_App_Checksum_Kit_JAVA.

Do we need to add external JAR files to make this work?
Why can't Paytm just provide maven dependency for this Checksum related jar?
I have searched all over the internet, It doesnt have any such maven dependency

**Comment by snehachandiyekar** [comment]
I don't know if this repository is valid anymore. 
I found their updated jar files here: [https://github.com/paytm/Paytm_JAVA_Checksum](https://github.com/paytm/Paytm_JAVA_Checksum)
